@startuml hello

class User{
    id 
    username
    passwd
}

class FriendLink{
    idL
    idR
}

class Album {
id
name
description
restrictMode
imageCount
}


class Image {
id
name
data
albumId
commentCount
tags
}

class Comment{
    userId
    imageId
    text
    data
}

@enduml