[package]
name = "kb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
suiron-rust = "0.1.0"
substring = "1.4.5"