DROP INDEX student_id_students_idx;
DROP INDEX username_posts_idx;
DROP INDEX chat_id_messages_idx;
DROP FUNCTION complete_quiz;
DROP FUNCTION complete_lesson;
DROP TRIGGER check_payment ON enrollments;
DROP TRIGGER course_complete_check ON feedbacks;
DROP TABLE messages;
DROP TABLE chats;
DROP TABLE progress CASCADE;
DROP TABLE feedbacks CASCADE;
DROP TABLE enrollments CASCADE;
DROP TABLE payments CASCADE;
DROP TABLE posts CASCADE;
DROP TABLE topics CASCADE;
DROP TABLE students CASCADE;
DROP TABLE groups CASCADE;
DROP TABLE instructors CASCADE;
DROP TABLE users CASCADE;
DROP TABLE cards CASCADE;
DROP TABLE quizzes CASCADE;
DROP TABLE lessons CASCADE;
DROP TABLE courses CASCADE;
DROP TABLE lang_resources CASCADE;
DROP TABLE langs CASCADE;