sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 5 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 10 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 15 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 20 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 25 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 30 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 35 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 40 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 45 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 50 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 55 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 60 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 65 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 70 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 75 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 80 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 85 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 90 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 95 -t 41s --metrics --perf 
sudo stress-ng --cpu 2 --cpu-method-queens --cpu-load 100 -t 41s --metrics --perf 
