/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package functions

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        val ln = Ln(0.00000001)
        assertEquals(ln.eval(2.0), 0.69314718056, 0.00000001)
    }
}
